version: '3'   # Compose ファイル形式
services:   # サービスの定義
  db:   # イメージ名
    image: mysql:5.7.22   # ベースイメージ
    environment:   # 環境変数の追加
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3316:3306'
    volumes:   # データの永続化領域を指定（マウント）　[ホストのディレクトリ:コンテナのディレクトリ]
      - ./db/mysql/volumes:/var/lib/mysql
      - ./mysql-confd:/etc/mysql/conf.d

  web:
    build: .   # Dockerfileの場所
    command: bundle exec rails s -p 3000 -b '0.0.0.0'   # コンテナ内で動かすコマンドを指定
    volumes:
      - .:/myapp
    ports:   # portの公開 [ホストのポート番号:コンテナのポート番号]
      - "3000:3000"
    depends_on:   # サービス間の依存関係を指定　dbのコンテナが開始されたら本サービスを起動する
      - db